# Generated by Django 4.1.4 on 2023-01-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Клиент')),
                ('client_status', models.CharField(blank=True, choices=[('S', 'Silver'), ('G', 'Gold'), ('P', 'Platinum')], max_length=1, null=True)),
                ('telegram_id', models.PositiveIntegerField(blank=True, null=True)),
                ('telegram_payload', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(max_length=2, verbose_name='Колличество')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_name', models.CharField(max_length=100, verbose_name='Наимерование')),
                ('category', models.CharField(choices=[('Coffee', 'Coffee'), ('Desert', 'Desert')], max_length=6, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty_p', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
                ('delivery', models.CharField(blank=True, choices=[('Самовынос', 'Самовынос'), ('Доставка в бизнес-центре', 'Доставка в бизнес-центре'), ('Доставка Яндекс такси', 'Доставка Яндекс такси')], max_length=100, null=True)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='svr.client', verbose_name='Клиент')),
                ('positions', models.ManyToManyField(related_name='coffee', through='svr.Extra', to='svr.position')),
            ],
        ),
        migrations.AddField(
            model_name='extra',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svr.order', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='extra',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svr.position', verbose_name='Каталог'),
        ),
    ]
