# Generated by Django 4.1.4 on 2023-01-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='qty',
            field=models.PositiveIntegerField(verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='position',
            name='qty_p',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
