# Generated by Django 4.1.4 on 2022-12-13 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='coffee',
            field=models.CharField(max_length=100, verbose_name='Кофе'),
        ),
        migrations.AlterField(
            model_name='desert',
            name='desert',
            field=models.CharField(max_length=100, verbose_name='Десерт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='desert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desert_order', to='svr.desert'),
        ),
    ]
