# Generated by Django 4.1.4 on 2022-12-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='qty',
            field=models.IntegerField(verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='position',
            name='category',
            field=models.CharField(choices=[('Coffee', 'Coffee'), ('Desert', 'Desert')], max_length=6, verbose_name='Категория'),
        ),
    ]
