# Generated by Django 4.1.4 on 2023-01-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svr', '0002_alter_client_client_status_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
