# Generated by Django 4.1.4 on 2023-01-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svr', '0002_alter_extra_qty_alter_position_qty_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='qty_p',
        ),
    ]
