# Generated by Django 4.1.4 on 2022-12-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svr', '0002_alter_extra_qty_alter_position_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra',
            old_name='position',
            new_name='position_name',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='name',
            new_name='position_name',
        ),
    ]
