# Generated by Django 4.1.4 on 2023-01-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svr', '0003_remove_position_qty_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='qty_p',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
