# Generated by Django 4.1.4 on 2023-01-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svr', '0004_position_qty_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='qty_p',
            new_name='qty',
        ),
    ]
