# Generated by Django 4.1.4 on 2022-12-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svr', '0004_rename_position_name_extra_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, choices=[('Самовынос', 'Самовынос'), ('Доставка в бизнес центре', 'Доставка в бизнес центре'), ('Доставка Яндекс такси', 'Доставка Яндекс такси')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
