# Generated by Django 4.1.4 on 2023-01-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svr', '0005_rename_qty_p_position_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='qty',
            new_name='qty_coffee',
        ),
    ]
