# Generated by Django 4.1.4 on 2023-01-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svr', '0006_rename_qty_position_qty_coffee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='qty_coffee',
            new_name='qty',
        ),
    ]
