# Generated by Django 4.1.4 on 2023-01-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svr', '0007_rename_qty_coffee_position_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='qty',
        ),
        migrations.AddField(
            model_name='position',
            name='qty_p',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=2, null=True),
        ),
    ]
