# Generated by Django 4.1.4 on 2023-01-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svr', '0010_remove_position_qty_p_position_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Клиент'),
        ),
    ]
