# Generated by Django 4.1.4 on 2023-01-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svr', '0011_alter_client_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Клиент'),
        ),
    ]
